# -*- coding: utf-8 -*-
"""foundation 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D-xrOtXhZWapmN7EsRKW6lM6cyl43wqZ
"""

# Smart Foundation Type Selection using Machine Learning

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# Sample Dataset
data = {
    "SBC":[220,180,120,70,300,90,250,150,60,200,110,280],
    "Floors":[1,2,3,5,2,6,1,4,8,3,5,2],
    "GroundWater":[5,4,2,1,6,1,5,3,1,4,2,6],
    "SoilType":["Sand","Clay","Clay","Silt","Rock","Clay",
                "Sand","Silt","Clay","Sand","Silt","Rock"],
    "BuildingLoad":[150,300,450,900,250,1200,180,600,1500,400,850,300],
    "Foundation":["Isolated","Combined","Raft","Pile","Isolated",
                  "Pile","Isolated","Raft","Pile","Combined","Raft","Isolated"]
}

df = pd.DataFrame(data)

# Encode Soil Type
soil_encoder = LabelEncoder()
df["SoilType"] = soil_encoder.fit_transform(df["SoilType"])

# Encode Foundation
foundation_encoder = LabelEncoder()
df["Foundation"] = foundation_encoder.fit_transform(df["Foundation"])

# Features and Target
X = df[["SBC","Floors","GroundWater","SoilType","BuildingLoad"]]
y = df["Foundation"]

# Split Data
X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.2,random_state=42)

# Train Model
model = RandomForestClassifier(n_estimators=100,random_state=42)
model.fit(X_train,y_train)

# Prediction
y_pred = model.predict(X_test)

print("Accuracy:",accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

# ---------- User Input ----------
print("\nEnter Building Details")

sbc = float(input("Soil Bearing Capacity (kN/m²): "))
floors = int(input("Number of Floors: "))
gw = float(input("Ground Water Level (m): "))
soil = input("Soil Type (Sand/Clay/Silt/Rock): ")
load = float(input("Building Load (kN): "))

soil = soil.title() # Convert input soil type to title case
soil = soil_encoder.transform([soil])[0]

sample = [[sbc,floors,gw,soil,load]]

prediction = model.predict(sample)

foundation = foundation_encoder.inverse_transform(prediction)

print("\nRecommended Foundation:", foundation[0])